### PR TITLE
link to website for API key

### PR DESCRIPTION
**Pull request by jchris**
I have no idea if this is valid Electron or how it looks on the screen, because for some reason my app already has my API key, so I don't know how to audition this page.

### CODE REVIEW

**Comment by alanshaw** [comment]
FYI

Screenshot 2022-04-08 at 10 43 23

**Comment by alanshaw** [comment]
Tweaked so it looks like this now:

Screenshot 2022-04-08 at 11 01 14

**Review by alanshaw — APPROVED** [review]

**Comment by jchris** [comment]
Currently is it possible for an organization to provision API keys that end users can use? Or would they just have to do it by giving the API key in their account a name that associates it with the end user?

**Comment by alanshaw** [comment]
We _could_ do this with UCANs right now...but I've made no provision for it here.

**Comment by jchris** [comment]
Would it require a change in NFTUp to support? Or just a change on the API key maker on the website?

**Pull request merged**
